on:
  push:

jobs:
  deploy:
    name: Deploy stack
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Check stack
        run: npm run cdk synth
      - name: Deploy stack
        run: npm run cdk deploy
